services:
  moblie-app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      -  "8081:8081" ## wont run without
      - "19000:19000" ## expo dev tools
      - "19001:19001" ## expo LAN for barcode
      - "19002:19002" ## expo tunnel
    volumes:
      - ./moblie:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_TUNNEL_SUBDOMAIN=myapp-docker